# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dsoo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dsoo
	pod 'SwiftLint', '~> 0.34'
	pod 'Alamofire'
  pod 'AlamofireNetworkActivityLogger', '~> 2.4'
	pod 'MBProgressHUD', '~> 1.1'
end
